[build]
# define our target json, so that we don't have to pass it to cargo all the time
target = "x86_64-rustos.json"

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
# recompile core and compiler_builtins, since we have no underlying kernel, e.g., Linux, that is
# already included
build-std = ["core", "compiler_builtins"]
# re-add memory related functions
build-std-features = ["compiler-builtins-mem"]
